services:
  - type: web
    name: backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
