services:
- type: web
  name: backend
  runtime: node
  rootDir: backend
  buildCommand: npm install
  startCommand: node server.js

- type: web
  name: app-community
  runtime: docker
  rootDir: community/docker
  dockerfilePath: ./Dockerfile
  dockerContext: .
  buildCommand: curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && apt-get install -y nodejs && npm install
  startCommand: node server.js
