services:
- type: web
  name: backend
  runtime: node
  rootDir: backend
  buildCommand: npm install
  startCommand: nodemon server.js

- type: web
  name: app-community
  runtime: docker
  rootDir: community/docker
  dockerfilePath: ./Dockerfile
  dockerContext: .
